### ISSUE TITLE
Missing closing files

### ISSUE THREAD

**Issue by ryancaicse** [fumiyas/hyperestraier-encore#3] opened 2021-12-24 08:58 UTC
`fopen("/dev/urandom", "rb")) != NULL` shoule be closed in the method `est_random`?
https://github.com/fumiyas/hyperestraier-encore/blob/3b09726c9b39998228fb0bcde5eec31fb0408e63/estraier.c#L4079-L4095

**Comment by ryancaicse** [comment] 2022-05-27 03:18
Could you take a look? Many thanks. @fumiyas

**Comment by fumiyas** [comment] 2022-05-27 07:41
Duplicate of #2.

**Closed as completed by fumiyas** 2022-05-27 07:41 UTC
